### PR TITLE
remove distutils

### LINKED ISSUE #37: python_configure fails with python 3.10
Since `distutils` package is deprecated and [this rule uses `distutils` to get python include path](https://github.com/pybind/pybind11_bazel/blob/72cbbf1fbc830e487e3012862b7b720001b70672/python_configure.bzl#L247), `python_configure` fails with python 3.10.

stderr:
```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
```

Related links:
* https://www.python.org/dev/peps/pep-0632/
* migration advice in pep 0632: https://www.python.org/dev/peps/pep-0632/#migration-advice
* https://github.com/pybind/pybind11_bazel/blob/72cbbf1fbc830e487e3012862b7b720001b70672/python_configure.bzl#L247
* My project using this rule and python 3.10: https://github.com/jeongukjae/nori-clone/runs/4776043260?check_suite_focus=true#step:5:53

### PR DESCRIPTION
**Pull request by jeongukjae**
Resolve #37

### CODE REVIEW

**Comment by mchinen** [comment]
See #37 for context.  distutils is deprecated and causes issues on python 3.10 on windows.  I think this should be merged.

**Comment by Mizux** [comment]
IMHO prefer to use a patch like it has been done in pybind11
* pybind/pybind11#3764

```py
import sys
USE_SYSCONFIG = sys.version_info >= (3, 10)
if USE_SYSCONFIG:
  import sysconfig as s
  library_paths = [s.get_path("purelib")]
else:
  from distutils import sysconfig as ds
  library_paths = [ds.get_python_lib()]\n
```

```py
import sys
USE_SYSCONFIG = sys.version_info >= (3, 10)
if USE_SYSCONFIG:
  import sysconfig as s
  print(s.get_path("include"))
else:
  from distutils import sysconfig as ds
  print(ds.get_python_inc())
```

**Comment by Mizux** [comment]
FYI https://github.com/google/or-tools/blob/master/patches/pybind11_bazel.patch
@Maintainer Googler I can do a CL instead if it's easier to integrate...

**Comment by jblespiau** [comment]
Thank you, done in https://github.com/pybind/pybind11_bazel/commit/c982636cc37431f4a347bcd23a9716da215eb62e

**Pull request closed without merging**
